Add hashicorp vault edc extension
catenax-ng/product-edc pull request #118
Opened 2022-05-10 09:54 UTC by bcronin90

<p>Brendan Cronin brendan.cronin@mercedes-benz.com, Mercedes Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</p>

2022-05-12 06:32 UTC, florianrusch-zf requested changes
Hey, I know it's still a Draft PR, but I already take a view and saw a view things, which could be improved.

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/pom.xml
> +        </dependency>
I think this are not test libraries or? If they are, the scope is missing. If they are not, then I would move it out of the test section

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/pom.xml
> +        </dependency>
Is here the test scope missing?

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/CreateHashicorpVaultEntryRequestPayload.java
> +  }
Strange indentation? Don't we use 4 spaces?

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/CreateHashicorpVaultEntryRequestPayload.java
> +class CreateHashicorpVaultEntryRequestPayload {
I would recommend to rename the class to not have a verb in it. This should be the `HashicorpVaultEntryRequest` class.

```suggestion
class HashicorpVaultEntryRequest {
```

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/CreateHashicorpVaultEntryResponsePayload.java
> +class CreateHashicorpVaultEntryResponsePayload {
```suggestion
class HashicorpVaultEntryResponse {
```

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultClient.java
> +                    }
You can get rid of this else if you return in the if body before:
```suggestion
                      return;
                    }
                    
                    GetHashicorpVaultEntryResponsePayload payload =
                        objectMapper.readValue(
                            body.string(), GetHashicorpVaultEntryResponsePayload.class);
                    String value =
                        Objects.requireNonNull(payload.getData().getData().get(SECRET_KEY));
                    future.complete(Result.success(value));
```

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/test/resources/logback.xml
> +</configuration>
Missing empty EOF

```suggestion
</configuration>

```

2022-05-12 06:32 UTC, florianrusch-zf commented on edc-extensions/pom.xml
>  </project>
Missing empty EOF

```suggestion
</project>

```

2022-05-12 06:32 UTC, florianrusch-zf commented on pom.xml
> +            </dependency>
Test scope?
```suggestion
            <dependency>
                <groupId>org.eclipse.dataspaceconnector</groupId>
                <artifactId>junit-extension</artifactId>
                <version>${org.eclipse.dataspaceconnector.version}</version>
                <scope>test</scope>
            </dependency>
```

2022-05-12 07:30 UTC, denisneuling commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/CreateHashicorpVaultEntryRequestPayload.java
> +  }
Atm we use [Google Java Style](https://google.github.io/styleguide/javaguide.html) resp. [spotless google-java-format](https://github.com/diffplug/spotless/tree/main/plugin-maven#google-java-format). But let's discuss using [Eclipse JDT](https://github.com/diffplug/spotless/tree/main/plugin-maven#eclipse-jdt) to be better aligned with the upstream EDC repo.

<sub>Denis Neuling <denis.neuling@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

2022-05-12 07:36 UTC, denisneuling commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/CreateHashicorpVaultEntryRequestPayload.java
> +class CreateHashicorpVaultEntryRequestPayload {
The hashicorp vault API expects different payloads for creating/updating keys, also it's not responding according to that structure, so I guess it's better to express explicitly what this class is used for. Furthermore IMHO `Request` indicates the object contains all details to construct a HTTP request object - including headers, uri, method etc. - which is not the case so I'd prefer keeping that within name. 


<sub>Denis Neuling <denis.neuling@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

2022-05-12 07:40 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/CreateHashicorpVaultEntryRequestPayload.java
> +class CreateHashicorpVaultEntryRequestPayload {
Ahhhh got it! Then I'm totally with you ;-) Thanks for explaining this!

2022-05-12 07:41 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/CreateHashicorpVaultEntryRequestPayload.java
> +  }
Then we will let it as it is and discuss this team internally 😉

2022-05-12 08:41 UTC, denisneuling commented on edc-extensions/hashicorp-vault/pom.xml
> +        </dependency>
Yeah, looks strange, but the scope here needs to be `test`... These dependencies are just used to see the test-containers logs. the extension itself uses the edc monitor and therefore is agnostic towards which logging subsystem is used.

2022-05-16 09:11 UTC, bcronin90 commented
@denisneuling Just lost Internet access. Using UMTS for now, but should be fixed by tomorrow. Can't use teams because it's too slow, but I'll get the remaining unit tests up to where we left the current one.

2022-07-27 14:14 UTC, denisneuling commented
@bcronin90 Shall we close this one?

2022-07-27 14:49 UTC, bcronin90 commented
> @bcronin90 Shall we close this one?

I think we can. Unless we want cert authentication any time soon. Which I'm not sure is required or worth it.

2022-07-27 14:49 UTC, closed without merging