Add hashicorp vault extension only with Token Auth
catenax-ng/product-edc pull request #175
Opened 2022-05-30 15:51 UTC by bcronin90

Basically the same as #118 but without Certificate Authentication. Please pay close attention to the control and data planes. I'm not sure how to properly test their correctness.

<sub>Brendan Cronin [brendan.cronin@mercedes-benz.com](mailto:brendan.cronin@mercedes-benz.com), Mercedes Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)</sub>

2022-06-03 13:35 UTC, denisneuling commented on edc-dataplane/edc-dataplane-hashicorp-vault/README.md
> +edc.vault.clientsecret=34-chars-secret
You're absolutely right. For some reason forgot to also apply these documentation chnageschanges to the dataplane derivative. Done now.

2022-06-07 09:28 UTC, ndr-brt reviewed
Seems quite good to me, I would just avoid the async stuff as is it brings unnecessary complexity.

2022-06-07 09:28 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultExtension.java
> +  private OkHttpClient createOkHttpClient(HashicorpVaultClientConfig config) {
`okHttpClient` can be injected as it is already registered in the `CoreServicesExtension` of the EDC

2022-06-07 09:28 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultExtension.java
> +    String vaultTimeoutString = context.getSetting(VAULT_TIMEOUT_SECONDS, "30");
Passing the default value as an `int` will made the setting already parsed to `int`

2022-06-07 09:28 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultExtension.java
> +      vaultTimeoutDuration = Duration.ofSeconds(vaultTimeoutInteger);
this operation cannot throw a `NumberFormatException`, better to move it directly on the builder object call (line 118)

2022-06-07 09:28 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultClient.java
> +  CompletableFuture<Result<String>> getSecretValue(@NonNull String key) {
As all the usages of the client (in the `HashicorpVault` class) are sync code, I would set the client as sync to, using the `okhttp` `execute` method instead of `enqueue`, this will simplify the design and the tests a lot.

2022-06-07 11:18 UTC, florianrusch-zf requested changes

2022-06-07 11:18 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultExtension.java
> +  @EdcSetting public static final String VAULT_TOKEN = "edc.vault.token";
Isn't this also required?
```suggestion
  @EdcSetting(required = true)
  public static final String VAULT_TOKEN = "edc.vault.token";

```

2022-06-07 11:18 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultExtension.java
> +  }
Do we need this function, also if we don't do anything here?

2022-06-07 11:18 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultExtension.java
> +
```suggestion
```

2022-06-07 11:18 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.VaultExtension
> +org.eclipse.dataspaceconnector.core.security.hashicorp.HashicorpVaultExtension
Why do we have the package structure `org.eclipse.dataspaceconnector`? We are at catenax so shouldn't we use `net.catena-x....`?

2022-06-07 11:20 UTC, florianrusch-zf commented on README.md
>  * [edc-controlplane-postgresql](edc-controlplane/edc-controlplane-postgresql)
We spoke about this in the sync call - if I remember it correctly, Stefan will rethinking this topic. Therefor I would suggest to do nothing here until he decide on something.

2022-06-07 11:20 UTC, florianrusch-zf commented on edc-controlplane/pom.xml
>          <module>edc-controlplane-memory</module>
We spoke about this in the sync call - if I remember it correctly, Stefan will rethinking this topic. Therefor I would suggest to do nothing here until he decide on something.

2022-06-07 11:21 UTC, florianrusch-zf commented on README.md
> +docker pull ghcr.io/catenax-ng/product-edc/edc-dataplane:latest
We spoke about this in the sync call - if I remember it correctly, Stefan will rethinking this topic. Therefor I would suggest to do nothing here until he decide on something.

2022-06-07 11:28 UTC, denisneuling commented on edc-extensions/hashicorp-vault/src/main/java/org/eclipse/dataspaceconnector/core/security/hashicorp/HashicorpVaultExtension.java
> +  private OkHttpClient createOkHttpClient(HashicorpVaultClientConfig config) {
I'd prefer using a custom instance of the okhttp client - in a subsequent PullRequest we will add functionality for TLS authentication, which basically means we need to add a custom SSLContext to the OkHttpClient - so we'll anyway use a dedicated client then.

2022-06-08 14:52 UTC, bcronin90 commented
@ndr-brt @florianrusch-zf We implemented most of the suggestions. Please have another look. Thanks!

2022-06-08 16:22 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVault.java
> +  public Result<Void> storeSecret(@NotNull @NonNull String key, @NotNull @NonNull String value) {
the implementation of this method could be one-liner, exploiting the `map` function on the `Result` object
```
    return hashicorpVaultClient.setSecret(key, value).map(it -> null)
```

2022-06-08 16:29 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultClient.java
> +    key = URLEncoder.encode(key, StandardCharsets.UTF_8);
these two lines (those who built the requestURI) are duplicated over all the methods, better have a method that builds the URI given the key

2022-06-08 16:29 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultClient.java
> +    Headers headers = headersBuilder.build();
A method that build header can be extracted, as the logic is the same over the three methods

2022-06-08 16:33 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultClient.java
> +      throw new HashicorpVaultException(e.getMessage(), e);
it should return failed `Result`

2022-06-08 16:33 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultClient.java
> +      throw new HashicorpVaultException(e.getMessage(), e);
it should return failed `Result`

2022-06-08 16:33 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultClient.java
> +      throw new HashicorpVaultException(e.getMessage(), e);
it should return failed `Result`

2022-06-08 16:36 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVaultClient.java
> +      response = okHttpClient.newCall(request).execute();
`Response` object is closable and it should be closed. Why don't do all the evaluation logic into an unique `try catch` block? e.g.
```
    try (var response = okHttpClient.newCall(request).execute()) {
        return response.isSuccessful() || response.code() == 404 
                ? Result.success() 
                : Result.failure(String.format(CALL_UNKNOWN_ERROR_TEMPLATE, response.code()));
    } catch (IOException e) {
      return Result.failure("Error during call:" + e.getMessage());
    }
```

(same for the other 2 methods)

2022-06-09 08:03 UTC, bcronin90 commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVault.java
> +    if (result == null) {
In case of a 404, the result would be null.

2022-06-09 08:13 UTC, bcronin90 commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVault.java
> +    if (result == null) {
Yeah, but maybe it shouldn't. Good point.

2022-06-09 08:26 UTC, florianrusch-zf requested changes

2022-06-09 08:26 UTC, florianrusch-zf commented on edc-dataplane/edc-dataplane-azure-vault/README.md
> +# EDC Data-Plane [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/#product-overview)
```suggestion
# EDC Data-Plane with [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/#product-overview)
```

2022-06-09 08:26 UTC, florianrusch-zf commented on edc-dataplane/edc-dataplane-hashicorp-vault/README.md
> +|---	                                                |---        |---	  |---          |
Still tabs within here

2022-06-09 08:26 UTC, florianrusch-zf commented on edc-dataplane/edc-dataplane-hashicorp-vault/README.md
> +| edc.controlplane.validation-endpoint                  | X         | http://controlplane:8182/validation | |
Related to my PR https://github.com/catenax-ng/product-edc/pull/193
```suggestion
| edc.controlplane.validation-endpoint                  | X         | http://controlplane:8182/validation/token | |
```

2022-06-09 08:26 UTC, florianrusch-zf commented on edc-dataplane/edc-dataplane-hashicorp-vault/README.md
> +edc.controlplane.validation-endpoint=http://controlplane:8182/validation
Related to my PR https://github.com/catenax-ng/product-edc/pull/193
```suggestion
edc.controlplane.validation-endpoint=http://controlplane:8182/validation/token
```

2022-06-09 08:28 UTC, florianrusch-zf commented
@bcronin90 It would be cool, if we can avoid doing force pushes if there are already reviews taken place - because then the github feature to just see changes since the last review isn't working any more which makes it hard to identified whats has changed within the 50 files 😅

2022-06-09 09:14 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVault.java
> +    if (result == null) {
@bcronin90 since the client is also in the same extension, they could agree on the fact that the `getSecretValue` should always return a `Result` object, no nulls, no exceptions, so that the vault could take its decisions without worrying about null checks or exception handling

2022-06-09 11:13 UTC, bcronin90 commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVault.java
> +  public Result<Void> storeSecret(@NotNull @NonNull String key, @NotNull @NonNull String value) {
I don't really like that change, since it's imo less readable. Or rather not immediately obvious what it does.

2022-06-09 11:17 UTC, bcronin90 commented
@ndr-brt @florianrusch-zf We implemented most of the suggestions. Please have another look. Thanks!

> @bcronin90 It would be cool, if we can avoid doing force pushes if there are already reviews taken place - because then the github feature to just see changes since the last review isn't working any more which makes it hard to identified whats has changed within the 50 files sweat_smile

Noted. Sorry for the confusion. I'll avoid such big squashes in the future.

2022-06-09 11:31 UTC, bcronin90 commented
@ndr-brt @florianrusch-zf @denisneuling Let's got for another round. I think I cleaned up everything.

2022-06-09 11:36 UTC, florianrusch-zf approved these changes

2022-06-09 11:50 UTC, ndr-brt commented on edc-extensions/hashicorp-vault/src/main/java/net/catenax/edc/hashicorpvault/HashicorpVault.java
> +  public Result<Void> storeSecret(@NotNull @NonNull String key, @NotNull @NonNull String value) {
I think the `map` method should be well digested by every java developer since it's on the `Stream` and on the `Optional` classes since java 8, but, well, just a matter of tastes I guess. :)

2022-06-09 11:51 UTC, ndr-brt approved these changes
Good for me!

2022-06-09 12:01 UTC, florianrusch-zf requested changes

2022-06-09 12:01 UTC, florianrusch-zf commented on deployment/helm/edc-dataplane/values.yaml
>      # edc.vault.tenantid=
Don't we have to remove this?

2022-06-09 12:01 UTC, florianrusch-zf commented on deployment/helm/edc-controlplane/values.yaml
>      # edc.vault.tenantid=
Don't we have to remove this?

2022-06-09 12:01 UTC, florianrusch-zf commented on deployment/helm/edc-dataplane/values.yaml
>      # edc.vault.tenantid=
Ah nevermind...it's depending on the container image :-/ I think this will lead to a lot of confusion :-(

2022-06-09 12:02 UTC, florianrusch-zf commented on deployment/helm/edc-dataplane/values.yaml
>      # edc.vault.tenantid=
@denisneuling @bcronin90 should we maybe rename the new configs to something like `edc.hasicorp.vault.*`?

2022-06-09 12:14 UTC, denisneuling commented on deployment/helm/edc-dataplane/values.yaml
>      # edc.vault.tenantid=
@florianrusch-zf Filesystem vault and azure vault share the same prefix, so why not doing the same for hashicorp vault? Multiple vault can't exist on the same edc executable anyway....

2022-06-09 12:15 UTC, denisneuling commented on deployment/helm/edc-controlplane/values.yaml
>      # edc.vault.tenantid=
If you ask me, we should update this block in another (documentation) Pull Requests, maybe explicitly stating which properties are needed to configure what subsystem/extension. Fine for you?

2022-06-09 13:38 UTC, denisneuling commented on deployment/helm/edc-dataplane/values.yaml
>      # edc.vault.tenantid=
Alright, got your point. Have renamed the properties to be prefixed with `edc.vault.hashicorp`.

2022-06-09 14:31 UTC, florianrusch-zf requested changes

2022-06-09 14:31 UTC, florianrusch-zf commented on edc-extensions/hashicorp-vault/README.md
> +| edc.vault.hashicorp.timeout.seconds | Request timeout in seconds when contacting the vault | |
```suggestion
| edc.vault.hashicorp.timeout.seconds | Request timeout in seconds when contacting the vault (default: 30) | |
```

2022-06-09 14:44 UTC, florianrusch-zf approved these changes

2022-06-09 14:49 UTC, merged