Add documentation to deploy EDC settings as k8 secrets
catenax-ng/product-edc pull request #253
Opened 2022-07-07 10:25 UTC by DominikPinsel

Signed-off-by: Dominik Pinsel <dominik.pinsel@daimler.com>

2022-07-07 12:28 UTC, florianrusch-zf requested changes

2022-07-07 13:40 UTC, DominikPinsel commented on edc-dataplane/README.md
> +While the **Control Plane** manages Data Transfer, the **Control Plane** is responsible for doing the actual data transfer, so that data is never routes through the control plane itself.
thanks for your review :) I really missed that

2022-07-07 13:41 UTC, DominikPinsel commented on edc-dataplane/README.md
> +[---]
Yea, that's better. I will change it :)

2022-07-07 13:43 UTC, DominikPinsel commented on edc-tests/src/main/resources/deployment/helm/all-in-one/templates/secret.yaml
> +type: Opaque
That's perfectly fine :) I've changed it

2022-07-07 13:44 UTC, DominikPinsel commented on edc-tests/src/main/resources/deployment/helm/all-in-one/templates/secret.yaml
> +  EDC_VAULT_HASHICORP_TOKEN: {{ $sokrates_vault_token | toString | quote }}
ah yea, I forgot this one :)

2022-07-08 07:38 UTC, denisneuling approved these changes

2022-07-08 07:46 UTC, merged