Introduce tractusx-connector helm chart
catenax-ng/product-edc pull request #541
Opened 2022-11-21 19:38 UTC by DominikPinsel

2022-11-22 11:43 UTC, DominikPinsel commented
> Still in progress of reviewing. Also hadn't the chance to look at the latest commits. Hope it's already helpful!

Always :) Thanks! Still a lot in progress here, I created the draft mainly to try out the new business test pipeline.

2022-11-22 11:48 UTC, DominikPinsel commented on charts/txdc/values.yaml
> +customLabels: { }
Yes, it accepts it.

2022-11-22 12:15 UTC, florianrusch-zf requested changes
Now I have looked at all the changes 🤣
Looks quite promising.

2022-11-22 12:15 UTC, florianrusch-zf commented on charts/txdc/values.yaml
> +  #   memory: 128Mi
```suggestion
    #   memory: 128Mi
```

2022-11-22 13:08 UTC, denisneuling commented on charts/txdc/templates/configmap.yaml
> +    otel.javaagent.debug=false
Of course it must - but it's still a draft

2022-11-23 11:11 UTC, denisneuling commented on charts/txdc/templates/deployment.yaml
> +
done.

2022-11-23 11:11 UTC, denisneuling commented on charts/txdc/templates/deployment.yaml
> +
done.

2022-11-25 11:06 UTC, florianrusch-zf commented on charts/txdc/values.yaml
> +    dapsPublicKey: daps-public-key
I know, that the EDC setting was named `EDC_OAUTH_PUBLIC_KEY_ALIAS` but the input is just a certificate. Would it make sense to rename this property here to `daps-public-cert` or something similar to reduce the confusions for the operation people?

2022-11-28 08:51 UTC, florianrusch-zf commented on charts/txdc/values.yaml
> +  name: ""
@denisneuling what's you opinion about this?

2022-11-29 08:43 UTC, florianrusch-zf commented on charts/txdc/templates/deployment-controlplane.yaml
> +              value: {{ .Values.postgresql.jdbcUrl | required ".Values.postgresql.jdbcUrl is required" | quote }}
The following is WIP!!

As far as I know, the database needs to be at the end of the jdbcUrl. E.g `jdbc:postgresql://my-postgres-postgresql:5432/asset`

Is it possible to leaf it away?? Can you double check this?

Within the documentation I found this (https://jdbc.postgresql.org/documentation/use/#connecting-to-the-database):

> The default is to connect to a database with the same name as the user name used to connect to the server.

Therefor I would say it's necessary to add the database name to the url

2022-11-29 10:42 UTC, ndr-brt commented on charts/txdc/values.yaml
> +    dapsPublicKey: daps-public-key
@florianrusch-zf I noted the same on upstream, I think it would be better to rename there also to avoid ambiguity

2022-11-29 12:39 UTC, denisneuling commented
> As already talked about in the chat, I noticed that many of the URLs are built depending on whether there is an Ingress or not. Don't know if that's so smart, or if we should include the possibility to override it. We at ZF for example have the use case that we don't create ingresses for our connectors.

@florianrusch-zf This now has been implemented for the IDS-API of the control-plane and for the "public" API of the data-plane. Is this fine enough or do we need to have this functionality as well for the other ones (data-management, control, validation etc)?

2022-11-29 14:40 UTC, florianrusch-zf commented
> @florianrusch-zf This now has been implemented for the IDS-API of the control-plane and for the "public" API of the data-plane. Is this fine enough or do we need to have this functionality as well for the other ones (data-management, control, validation etc)?

@denisneuling fine for me ;-)

2022-11-29 15:11 UTC, florianrusch-zf approved these changes

2022-11-30 10:53 UTC, florianrusch-zf commented on charts/txdc-connector/Chart.yaml
> +name: txdc-connector
Was thinking that `txdc` was standing for `Tractus-X Dataspace Connector`. So we would now have `Tractus-X Dataspace Connector connector` 😅 which makes no sense.

What is the meaning of the `txdc` abbreviation?

2022-11-30 11:13 UTC, DominikPinsel commented on charts/txdc-connector/Chart.yaml
> +name: txdc-connector
yes :) its now tractusx-connector

2022-11-30 14:20 UTC, merged