update sample docu
catenax-ng/product-edc pull request #671
Opened 2023-01-13 11:59 UTC by DominikPinsel

2023-01-16 08:06 UTC, florianrusch-zf requested changes

2023-01-16 08:06 UTC, florianrusch-zf commented on docs/samples/Transfer Data.md
>  5. Verify Data Transfer
We should also link this entries

2023-01-16 08:06 UTC, florianrusch-zf commented on docs/samples/Transfer Data.md
> +Environment Variables, used by this example' below.
The subchapter should also be linked

2023-01-16 08:06 UTC, florianrusch-zf commented on docs/samples/Transfer Data.md
> +The most important APIs, used by this example, are highlighted. How they are used is described in subchapter 'Set
Again, link the subchapter 😉

2023-01-16 08:06 UTC, florianrusch-zf commented on docs/samples/Local TXDC Setup.md
> +everything to run two connectors independently.
```suggestion
Before the connectors can be setup, the Supporting Infrastructure must be in place. It comes with pre-configured everything
to run two connectors independently.
```

2023-01-16 11:01 UTC, ndr-brt commented on docs/samples/Transfer Data.md
> +|             |                       | data/8081       | http://192.168.49.2:30423 | < Plato Data Management API
the "data" term has been dropped to avoid misunderstandings, now it's called only "management api".

2023-01-25 15:53 UTC, florianrusch-zf commented on docs/samples/Transfer Data.md
> +|             |                       | data/8081       | http://192.168.49.2:30423 | < Plato Data Management API
@ndr-brt @tuncaytunc-zf should we adopt this change maybe in a separate PR for the whole repo?

2023-01-25 15:54 UTC, florianrusch-zf commented
As @DominikPinsel is OOO, I will take it over 😉

2023-01-30 08:22 UTC, florianrusch-zf commented on docs/samples/Transfer Data.md
>  5. Verify Data Transfer
```suggestion
0. [(optional) Local Setup](#0--optional--local-setup)
1. [Setup Data Offer](#1-setup-data-offer)
2. [Request Contract Offers](#2-request-contract-offer-catalog)
3. [Negotiate Contract](#3-negotiate-contract)
4. [Transfer Data](#4-transfer-data)
5. [Verify Data Transfer](#5-verify-data-transfer)
```

2023-01-30 08:23 UTC, florianrusch-zf commented on docs/samples/Transfer Data.md
> +Environment Variables, used by this example' below.
```suggestion
The most important APIs, used by this example, are highlighted. How they are used is described in subchapter ['Set
Environment Variables](#set-environment-variables-used-by-this-example), used by this example below.
```

2023-01-30 08:24 UTC, florianrusch-zf commented on docs/samples/Transfer Data.md
> +Environment Variables, used by this example' below.
```suggestion
The most important APIs, used by this example, are highlighted. How they are used is described in subchapter ['Set
Environment Variables](#set-environment-variables-used-by-this-example), used by this example below.
```

2023-01-30 08:26 UTC, florianrusch-zf approved these changes

2023-01-31 10:36 UTC, merged