Feature/cp adapter scaling rebased
catenax-ng/product-edc pull request #678
Opened 2023-01-16 10:30 UTC by marcingajek-zf

2023-01-16 11:26 UTC, florianrusch-zf requested changes
Just reviewed the changes in the documentation so far

2023-01-20 14:45 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/README.md
> +| edc.cp.adapter.reuse.contract.agreement          | Turn on/off reusing of existing contract agreements for the specific asset. Once the contract is agreed, the second request for the same asset wil
changed, thanks

2023-01-20 14:45 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/README.md
> +<h2><u>Configuration:</u></h2>
changed

2023-01-20 14:45 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/README.md
> +<h2><u>How to use it:</u></h2>
changed

2023-01-23 06:21 UTC, florianrusch-cluetec commented on edc-extensions/control-plane-adapter/README.md
> +To run CP-Adapter in "PERSISTENT" mode, You need to create a proper tables with [this](docs/schema.sql) script, and add the following configuration values to Your control-plane EDC properties file:
@DominikPinsel can we handle  this initial db initialisation somehow with the migration extension?

I think we should avoid, that the operator has to do something manually in the DB (expect creating DBs)!

2023-01-23 09:07 UTC, florianrusch-zf requested changes

2023-01-27 16:00 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/README.md
>     | contractAgreementReuse | Similar to <i>edc.cp.adapter.reuse.contract.agreement</i> option allows to turn off reusing of existing contracts, but on a request level. Set the parameter value to '0'
Those are optional parameters (explained above the table), like:
`/adapter/asset/sync/{assetId}?providerUrl={providerUrl}**&contractAgreementId=abc**`
So if there is no parameter, new contract agrement will be negotiated

2023-01-27 16:09 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/messaging/SqlMessageBus.java
> +    }
totally agree :)

2023-01-30 09:36 UTC, florianrusch-zf commented on edc-extensions/control-plane-adapter/README.md
>     | contractAgreementReuse | Similar to <i>edc.cp.adapter.reuse.contract.agreement</i> option allows to turn off reusing of existing contracts, but on a request level. Set the parameter value to '0'
My comment was regarding the type change to boolean.

2023-01-30 09:58 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/README.md
>     | contractAgreementReuse | Similar to <i>edc.cp.adapter.reuse.contract.agreement</i> option allows to turn off reusing of existing contracts, but on a request level. Set the parameter value to '0'
Oh, sorry, I've focused on the red/green code change shown above Your comment. Yes, You are correct, I will change it to boolean as well

2023-01-30 12:55 UTC, ndr-brt reviewed
Looks pretty much good, I would suggest to add an end to end test that verifies all the components integration

2023-01-30 12:55 UTC, ndr-brt commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlObjectStore.java
> +            return executeQuery(connection, false, this::mapObjectEntity, sql, type)
As the `executeQuery` documentation states, the `Stream` returned need to be closed explicitly after collection to close the sql connection/statement/resultset properly.

2023-01-31 10:47 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/messaging/SqlMessageBus.java
> +  private void deliverMessage(QueueMessage queueMessage) {
Looks to me that we have 3 different scenarios, and every one has single call to db:
1) message processed, than delete
2) message not processed and can not retry, than delete
3) message not processed but can retry, than update
Considering that I see no need for transaction :)

2023-01-31 13:25 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlObjectStore.java
> +            return executeQuery(connection, false, this::mapObjectEntity, sql, type)
fixed, thanks

2023-01-31 14:47 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/docs/schema.sql
> +
done

2023-01-31 14:47 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/ApiAdapterExtension.java
> +          "Persistent layer configuration is missing. Starting ObjectStore in 'IN MEMORY' mode.");
done

2023-01-31 14:48 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/ApiAdapterExtension.java
> +  }
changed

2023-01-31 14:48 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/README.md
> +   | contractAgreementId    | Defines the ID of existing contract agreement, that should be reused for retrieving the asset. If parameter is specified, but contract is not found, 404 error will be re
We can do it but I wouldn't block this PR withou it

2023-01-31 14:48 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/messaging/SqlMessageBus.java
> +    }
changed

2023-01-31 14:48 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/messaging/SqlMessageBus.java
> +      monitor.debug("[%s] Message sent and removed." + queueMessage.getId());
changed

2023-01-31 14:49 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/messaging/SqlMessageBus.java
> +    monitor.debug("Found " + queueMessages.size() + " messages to send.");
fixed

2023-02-07 11:30 UTC, marcingajek-zf commented
@ndr-brt please take a look if the PR can be merged.

2023-02-07 13:18 UTC, ndr-brt reviewed
As I said in the previous I think an integration test that verifies all the flow from start to end.
Also tests on the `Sql` stores implementation would be important to verify mappings and queries

2023-02-07 13:18 UTC, ndr-brt commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
This class seems to be not tested, I would suggest at least a save/retrieve test against a sql server to verify mapping and queries.

2023-02-07 15:08 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
It's not tested as I've cretaed only unit test for the classes with logic. SqlQueueStore is a utily class.

Integration tests are created within: https://jira.catena-x.net/browse/A1IDSC-393

Task is inprogress, and I believe there could be tests that make use of DB to test if reads/writes are correct

2023-02-07 15:22 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/messaging/SqlMessageBus.java
> +  private void deliverMessage(QueueMessage queueMessage) {
The idea is, that if anything breaks during processing of the message, the message should not be deleted. The delivery should be retried, and message is deleted only if it is successfully processed.

I follow the rule of "At-least-once Delivery".

If during the process of message1 some other other message2 was send, and then we have an error - message1 will be retried. In this corner case scenario some actions may be duplicated, but the process should be delivered as expected.

2023-02-07 15:37 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/README.md
> +To run CP-Adapter in "PERSISTENT" mode, You need to create a proper tables with [this](docs/schema.sql) script, and add the following configuration values to Your control-plane EDC properties file:
done

2023-02-08 08:26 UTC, ndr-brt commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/messaging/SqlMessageBus.java
> +  private void deliverMessage(QueueMessage queueMessage) {
ok, fine for me

2023-02-08 08:28 UTC, ndr-brt commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
Business tests are a little far from the logic and hard to debug, I'm not in favor of delegating integration tests against DB to the E2E layer because this could become tedious

2023-02-08 09:58 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
@ndr-brt 
But unit test are also not good place for testing integration with DB. 
Do You know some example in product-edc where this kind of DB test is cerated?

2023-02-09 07:33 UTC, ndr-brt commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
this is actually the first time we have a sql store in product edc, but in EDC they are well tested, e.g.:
https://github.com/eclipse-edc/Connector/blob/main/extensions/control-plane/store/sql/asset-index-sql/src/test/java/org/eclipse/edc/connector/store/sql/assetindex/PostgresAssetIndexTest.java

there the test suites are separated by meaning: unit tests, postgres integration tests, daps integration tests, ...
a good practice is to follow the "fail fast" pattern, furthermore business tests should test business, so e2e use cases, not integration.

2023-02-09 10:37 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
Ok, I was not aware that there are test in EDC that uses real DB during test run. 
Looks to me that I can not use the "testFixtures" from core edc and the whole db setup. 
I understand that You expect me to set it all up for product-edc? 
I'm asking as I'm starting to have some doubts if this will be ready for next release.

2023-02-09 11:19 UTC, ndr-brt commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
I'm not really inclined to have features that aren't duly covered but, if we're sure that this works, good for me. I will just approve the PR, eager to see a subsequent one that covers the missing tests.

2023-02-09 11:20 UTC, ndr-brt approved these changes

2023-02-09 12:37 UTC, marcingajek-zf commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
Thank You Andrea,
I really appreciate all Your comments, they are very usefull. I will try to add such test in future. Hope to find someone that knows how those EDC test works, as for now they are failing when I run them. Maybe there is some additional config that I've missed, but I would expect that running a method with @Test annotation should be enough...

2023-02-09 13:59 UTC, ndr-brt commented on edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
> +public class SqlQueueStore extends AbstractSqlStore {
to run them you should either add the `includeTags` property as it's done by the ci workflow:
https://github.com/eclipse-edc/Connector/blob/main/.github/workflows/verify.yaml#L212
or to comment the `@PostgresqlIntegrationTest` annotation.

I usually do the latter during development :)

2023-02-10 11:17 UTC, marcingajek-zf commented
@florianrusch-zf  is it ok for You to mrege the PR ?

2023-02-17 05:39 UTC, merged