EDC - Create Business Tests for Wrapper Extension
catenax-ng/product-edc pull request #704
Opened 2023-01-30 15:01 UTC by diegogomez-zf

- add cucumber tests
- add test datasets (example submodels)

2023-02-01 08:08 UTC, tuncaytunc-zf commented
Hi Diego, maybe your tests get ignored because of wrong file extention, the "EndToEndTransfer.Feature" should be "EndToEndTransfer.**f**eature" the file extention should be start with small letter but I'm not sure it this is the only reason.

2023-03-06 08:36 UTC, DominikPinsel requested changes

2023-03-06 08:36 UTC, DominikPinsel commented on edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/ControlPlaneAdapterSteps.java
> +  @Then("'{connector}' asks for the asset from the endpoint")
As the connector/consumer argument is not used by the method, it would probably increase the readability if we remove it.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 08:36 UTC, DominikPinsel commented on edc-tests/src/test/resources/org/eclipse/tractusx/edc/tests/features/EndToEndTransfer.feature
> +#TODO
Maybe you can link this issue here and mention, that its currently not running because of a possible race condition in the CI pipeline, regarding the contract validity
https://github.com/eclipse-edc/Connector/issues/2514

2023-03-06 08:36 UTC, DominikPinsel commented on edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/DataManagementAPI.java
> +    log.info("path to ask for Asset" + path);
I assume this logging was created for troubleshooting and can be removed now?

2023-03-06 08:36 UTC, DominikPinsel commented on edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/DataManagementAPI.java
> +    log.info("EndpointDataReference in CreateContractDefinition" + endpoint.getEndpoint());
I assume this logging was created for troubleshooting and can be removed now?

2023-03-06 13:11 UTC, diegogomez-zf commented on edc-tests/src/test/java/org/eclipse/tractusx/edc/tests/ControlPlaneAdapterSteps.java
> +  @Then("'{connector}' asks for the asset from the endpoint")
@DominikPinsel Do you mean to really remove it or just to comment it?. Because this is the method is related to the step Then 'Sokrates' asks for the asset from the endpoint in the EndToEndTransfer.feature file.

2023-03-07 07:14 UTC, DominikPinsel approved these changes

2023-03-07 07:26 UTC, merged