Add contract id to data source http call
catenax-ng/product-edc pull request #732
Opened 2023-02-09 08:58 UTC by ndr-brt

### what
provides a provision extension to enrich the `HttpDataAddress` with an header containing the contract id

### why
to being able to forward that information to the backend data source

### how
registers a resource definition and a provisioner that on the provider side will modify the content data address adding the contract id header: `Edc-Contract-Id`

2023-02-09 10:08 UTC, tuncaytunc-zf approved these changes

2023-02-09 12:23 UTC, florianrusch-zf requested changes

2023-02-09 12:23 UTC, florianrusch-zf commented on edc-extensions/provision-additional-headers/README.md
> +to retrieve the data to be given to the consumer.
Maybe this changes will make it a little bit easier to read:
```suggestion
The goal of this extension is to provide additional headers to the request to the backend service done by the provider
in order to retrieve the data that will be given to the consumer.
```

2023-02-09 12:23 UTC, florianrusch-zf commented on edc-extensions/provision-additional-headers/README.md
> +- `Edc-Contract-Id`: the id of the contract agreement
I'm already not a big fan about the naming of the contract agreement id field in the transfer process (if I'm right, it's simply `contract`). Wouldn't it be more intuitive to name it after what it is?

```suggestion
- `Edc-Contract-Agreement-Id`: the id of the contract agreement
```

Or maybe an alternative to make it shorter:

```suggestion
- `Edc-Agreement-Id`: the id of the contract agreement
```

2023-02-09 12:23 UTC, florianrusch-zf commented on edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinitionGeneratorTest.java
> +    assertThat(result).isFalse();
Shouldn't we add the opposite of this also to the second test in this class?

2023-02-09 13:05 UTC, ndr-brt commented on edc-extensions/provision-additional-headers/README.md
> +- `Edc-Contract-Id`: the id of the contract agreement
In the DataRequest it is called `contractId`, I think in the transfer process context it's implicit that we're speaking about the contract agreement id

2023-02-09 16:07 UTC, florianrusch-zf commented
side note: on consumer side the EDR contains a parameter with the name `cid` which contains the agreement id (?)

2023-02-09 16:16 UTC, ndr-brt commented
> side note: on consumer side the EDR contains a parameter with the name `cid` which contains the agreement id (?)

yes, but that can't be usable in the data-plane-http because it get lost before

2023-02-10 06:17 UTC, florianrusch-zf commented
> > side note: on consumer side the EDR contains a parameter with the name `cid` which contains the agreement id (?)
> 
> yes, but that can't be usable in the data-plane-http because it get lost before. I mean, there's no injection point where we can make use of that field to be put in the request

Yes, that was my guess too, of course. My intention last evening was just to document that we now have different names for the same field for somehow the same purpose. We should be as consistent as possible to avoid as much confusion as possible for end users and operators.

2023-02-13 13:39 UTC, florianrusch-zf commented on edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisioner.java
> -                .resourceName(UUID.randomUUID().toString()) // TODO: why is this mandatory?
Do you found the answer for this todo? :D

2023-02-13 13:42 UTC, ndr-brt commented on edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisioner.java
> -                .resourceName(UUID.randomUUID().toString()) // TODO: why is this mandatory?
lol, in fact yes, will remove that comment, is it ok for the rest?

2023-02-13 13:44 UTC, florianrusch-zf approved these changes

2023-02-13 13:46 UTC, florianrusch-zf commented on edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisioner.java
> -                .resourceName(UUID.randomUUID().toString()) // TODO: why is this mandatory?
The comment was already removed, that's why I'm asking :D
Would you like to share, why this uuid is needed? Or for what?

2023-02-13 13:46 UTC, merged