docs: create decision record about testing
catenax-ng/product-edc pull request #781
Opened 2023-02-27 08:27 UTC by paullatzelsperger

This PR contains the decision record about how testing should work in product-etc

2023-02-27 13:14 UTC, ndr-brt commented on docs/development/decision-records/2023-02-27_testing/README.md
> +This section is largely taken from the [EDC's testing documentation](https://github.com/eclipse-edc/Connector/blob/bab97cccf4d61a3a380a1d70925b34f4cec1b401/docs/developer/testing.md) with a few amend
some of the points are using singular and some others the plural, would be good to uniform

2023-02-27 13:14 UTC, ndr-brt commented on docs/development/decision-records/2023-02-27_testing/README.md
> +- **end-to-end-test**: similar to system tests, but they involve several connectors plus external services such as databases, identity providers, objects stores, etc. For example, one connector start
I would add that, in our case the end-to-end-tests are used to verify business requirements from an user perspective (hitting external exposed apis of the system)

2023-02-27 13:23 UTC, paullatzelsperger commented on docs/development/decision-records/2023-02-27_testing/README.md
> +This section is largely taken from the [EDC's testing documentation](https://github.com/eclipse-edc/Connector/blob/bab97cccf4d61a3a380a1d70925b34f4cec1b401/docs/developer/testing.md) with a few amend
oh, good catch, thx.

2023-02-27 13:34 UTC, ndr-brt approved these changes

2023-03-01 13:32 UTC, tuncaytunc-zf approved these changes

2023-03-06 10:48 UTC, DominikPinsel requested changes

2023-03-06 10:48 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-27_testing/README.md
> +It is a [well-established](https://martinfowler.com/articles/practical-test-pyramid.html) fact that unit tests should make up for the majority of tests, because they are easy and quick to write and q
We should only track the actual decisions in a decision record. This is very general testing know how. Maybe you can remove this section.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:48 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-27_testing/README.md
> +Furthermore, a finer-grained test classification such as the one outlined in this document is currently neither present nor documented.
Actually this is not true. The EDC is fully debuggable, and with a little bit of scription quite easy to set up. Please look at the CI pipeline, that setups two fully running EDCs in minutes, to understand how.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:48 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-27_testing/README.md
> +eventually we might want to write an integration test that uses a (containerized) PostgreSQL test instance.
This is very general testing know-how, probably everybody agrees to. Maybe you can reformulate it, so that it reflects better what should be decided here.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:48 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-27_testing/README.md
> +EDC provides a way to launch (multiple) embedded connector runtimes from within the JVM using the JUnit runner, see [this module](https://github.com/eclipse-edc/Connector/tree/main/system-tests/e2e-t
In regards to the different test categories. Currently there are multiple tests for the extensions developed here, that run in the local JVM. At the time of writing this are unit-, component- and integration tests. 

Then there are the business tests, that are basically automated smoke tests.

These tests cover already the things, that are developed in this repository. Of course I see how it is always possible to test more or better (please don't understand me wrong). I'm just not sure what these additional tests, that you suggest here, are excatly and what they test. If they test our extensions, that is already possible within the JVM. If they want to replace our smoke tests, unfortunatelly this is not possible with just the JVM.
Maybe you have an example for such a test?

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:48 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-27_testing/README.md
> +External systems such as databases or identity providers should be setup "out-of-band" of the test, using a script or the CI pipeline's declarative syntax (e.g. GitHub Actions' `services` feature). I
An always-on database does not decrease the potential for conflict. It increases it by introducing a dependency between the tests and test runs. For example: A test that creates an invalid EDC Asset (that makes it for the EDC impossible to send out catalog) would destroy all future test runs, on all branches, on all releases. This could also introduce race conditions between the tests. 
Additionally, we need a way to handle the different database schemas, the EDC introduces every few weeks. And probably more.
Test runs should be independend, and this is a prime example why.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:48 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-27_testing/README.md
> +| Performance test       | Only on a specific schedule, e.g. once per day or week                              |         |
Before anything is merged into the develop/main branch it must pass **all** tests. I see now way arround this. 

And before the merging of a PR, the owners of the Pull Request should be able to decide how they want to test. We are in no position to tell them how to work.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-07 18:29 UTC, jimmarino approved these changes

2023-03-16 09:27 UTC, merged