docs: decision record about the release process
catenax-ng/product-edc pull request #782
Opened 2023-02-27 08:33 UTC by paullatzelsperger

This PR contains a decision record about the adaptations needed to make the product-edc build more repeatable and in line with established practices.

2023-02-27 13:26 UTC, ndr-brt commented on docs/decision-records/2023-02-09-release-process/README.md
> +Up until now, the only way out was cherry-picking, which is extremely cumbersome and error-prone, and requires a
in fact, cherry-picking was only used for special cases like described in the last paragraph of the "Use release versions of EDC in releases", this decision doesn't change that, so I would remove this two lines.

2023-02-27 13:26 UTC, ndr-brt commented on docs/decision-records/2023-02-09-release-process/README.md
> +Unfortunately there is no way to automatically trigger the product-edc build whenever a new EDC nightly is
Dependabot could be used

2023-02-27 13:47 UTC, paullatzelsperger commented on docs/decision-records/2023-02-09-release-process/README.md
> +Up until now, the only way out was cherry-picking, which is extremely cumbersome and error-prone, and requires a
yes, but now we'd have alternative options, i.e. upgrading to newer EDC releases. cherrypicking is only necessary if those newer releases introduce breaking changes.

2023-02-27 14:11 UTC, ndr-brt commented
@paullatzelsperger seems that the [last commit](https://github.com/catenax-ng/product-edc/pull/782/commits/c641045508fc8a4f62f6ac47e0a07532942601ae) deleted the document

2023-02-27 14:13 UTC, paullatzelsperger commented
> @paullatzelsperger seems that the [last commit](https://github.com/catenax-ng/product-edc/pull/782/commits/c641045508fc8a4f62f6ac47e0a07532942601ae) deleted the document

you are correct. I had it in my staging area, so I could re-add it again, but have zero clue as to why that happened :/

2023-02-27 14:33 UTC, ndr-brt approved these changes

2023-03-06 10:15 UTC, DominikPinsel requested changes

2023-03-06 10:15 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-09-release-process/README.md
> +_Other guidelines w.r.t. the review process, merging etc. will follow in a later DR._
We can add such a section/comment when there is a corresponding decision record. We don't know yet when we will get there, so maybe we can remove it for now.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:15 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-09-release-process/README.md
> +readability and make a release's history readily apparent.
If we document that we use GitFlow, this section should become obsolete. Am I right?

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:15 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-09-release-process/README.md
> +current date, we can start the nightly. If the EDC nightly doesn't appear within a set timeframe, we throw an error.
The scope of this repository is not to build a connector for the latest EDC version, but to provide a connector for Catena-X. Normally this includes using **not** the lates EDC version, as long as we are not sure there are no issues with it.

We also don't do this for our other dependencies. Maybe you can elaborate why we should do this.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 10:15 UTC, DominikPinsel commented on docs/development/decision-records/2023-02-09-release-process/README.md
> +  publish.
This section does not contain a decision, so maybe we can remove it. After this repository is migrated to Tractus-X this section will no require dedicated decision, as its a basic Eclipse requirement.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-07 18:28 UTC, jimmarino approved these changes

2023-03-08 15:24 UTC, tuncaytunc-zf approved these changes

2023-03-13 06:58 UTC, florianrusch-zf requested changes

2023-03-13 06:58 UTC, florianrusch-zf commented on docs/development/decision-records/2023-02-09-release-process/README.md
> +# Release process of product-edc
shouldn't we already use the term `tractusx-edc`?

2023-03-13 06:58 UTC, florianrusch-zf commented on docs/development/decision-records/2023-02-09-release-process/README.md
> +  and concise reason to do so.
```suggestion
  is a clear and concise reason to do so.
```

2023-03-13 06:58 UTC, florianrusch-zf commented on docs/development/decision-records/2023-02-09-release-process/README.md
> +parallel build pipeline to publish the cherry-picked artifacts of EDC (and potentially others). With the approach presented here, cherry-picking is still an option, but there are easier alternatives
```suggestion
parallel build pipeline to publish the cherry-picked artifacts of EDC (and potentially others). With the approach
presented here, cherry-picking is still an option, but there are easier alternatives to it. 
```

2023-03-15 10:48 UTC, florianrusch-zf requested changes
Two points:
1. There are still comments from @DominikPinsel open which are in my eyes valid to discuss.
2. The text still uses the wording `product-edc` in some places. @stefan-ettl can you confirm that we need to replace it with tractusx-edc?

2023-03-15 11:02 UTC, paullatzelsperger commented
> Two points:
> 
> 1. There are still comments from @DominikPinsel open which are in my eyes valid to discuss.

Most questions that are asked are either beyond the scope of this D-R (e.g. why forking is necessary in Eclipse), are basic knowledge of the Maven release process (e.g. what exactly a `-SNAPSHOT` version is), are based on a misunderstanding (cf. the first comment about the scope being much larger) or are simply not actionable. 
And to be clear, the general content of this decision record was agreed on during the on-site meeting on Feb 8 2023.

In addition, there are already 3 approvals on this PR, which - going by majority vote - would already warrant a merge.

> 2. The text still uses the wording `product-edc` in some places. @stefan-ettl can you confirm that we need to replace it with `tractusx-edc`?

I think replacing `product-edc` should be done in one fell swoop and not piece-by-piece. as far  as it concerns this PR I've replaced all occurrences of "product-edc" with "tractusx-edc".

2023-03-16 17:42 UTC, closed without merging