docs: decision record build
catenax-ng/product-edc pull request #795
Opened 2023-03-06 07:43 UTC by paullatzelsperger

This PR adds a decision-record regarding the build system of `product-edc`.

2023-03-06 08:24 UTC, stephanbcbauer approved these changes
LGTM

2023-03-06 08:29 UTC, DominikPinsel requested changes

2023-03-06 08:29 UTC, DominikPinsel commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +  errors
Without very good reason to do so, changing the build system is not a good idea. You wrote some pro arguments in your decision record. Maybe you can point me to the argument, why it is really mandatory to change to Gradle.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

2023-03-06 09:02 UTC, ndr-brt approved these changes

2023-03-06 10:39 UTC, denisneuling reviewed
There are numerous different build tools in use within the catena-x ecosystem, which all result in the aforementioned outcome. This project uses maven, which does it's task well.
Solving an non-existent problem with the build tool seems to be needless effort as well as driven by personal preferences.

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +- default module dependencies
that's what `dependencies` and `dependencyManagement` are used for in maven

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +- default configuration (POM, Swagger, artifact signing, code style,...)
thats what the `plugin` and `pluginManagement` in parent poms are used for in maven

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +- default plugins for project submodules
that's what's done in parent poms, see `plugin`and `pluginManagement.

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +- publishing to artifact repositories (OSSRH/Sonatype and Maven)
that's done via the maven-release-plugin

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +- unified and core-maintained version catalogs and version resolution strategies to avoid version clashes and runtime
that's a core feature of maven, see dependency management and dependency mediation

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +executable code, a high degree of customization, optimization and modularization is possible.
That's just hypothetical. the way maven is configured to execute the build is declarative where the way its done with gradle is a mixture of declaration and programming - readability is not improved by higher level of given customization, in fact it becomes more error prone and time consuming to understand how projects using gradle are built

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +parallelization resulting in faster and more responsive builds.
These are core features of maven and have already been solved years before

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +- generate docker images using [this plugin](https://github.com/bmuschko/gradle-docker-plugin)
there was a good reason a plugin not to be dependant on the dockerd api. furthermore building and tagging a docker image is just `docker build` and `docker tag`.

2023-03-06 10:39 UTC, denisneuling commented on docs/development/decision-records/2023-03-02_gradle_build/README.md
> +- convert maven profiles -> JUnit tags (cf. EDC): run tests using JUnit `@Tag`s and the `includeBuild` feature
That's functionality included with the surefire plugin. Rather than using `includeBuild` the project must use dependencies deployed to repositories in a stable fashion. building git submodules or similar does not contribute to reproducibility

2023-03-06 13:36 UTC, tuncaytunc-zf commented
I think you can't say the one or the other tool is better than the other one. As Denis already described, you can do almost everything also with maven. The only benefit using Gradle in our project I see is having the same tool for both projects, where most of us are working in parallel and not to deal with huge xml files.
On the other hand, we have already a well running tool and we have to think if we have any real reason or pain point to change the current tool and have to think if it is really worth to spend time to convert/change it. Where to be honest, I don't see anyone yet, even I'm more Gradle fan :-)

2023-03-06 13:58 UTC, tuncaytunc-zf reviewed
I think you can't say the one or the other tool is better than the other one. As Denis already described, you can do almost everything also with maven. The only benefit using Gradle in our project I see is having the same tool for both projects, where most of us are working in parallel and not to deal with huge xml files.
On the other hand, we have already a well running tool and we have to think if we have any real reason or pain point to change the current tool and have to think if it is really worth to spend time to convert/change it. Where to be honest, I don't see anyone yet, even I'm more Gradle fan :-)

2023-03-07 18:28 UTC, jimmarino approved these changes

2023-03-09 16:44 UTC, stefan-ettl commented
Decision will finally Go towards Gradle. 
Reason: It's not about the question "what is better" it's about 
1) New Strategic path - regarding TractusX-EDC we have to move towards open source, but not just as a single product but in line with the eclipse-edc. There we want to align with automation features, publishing artifacts, testing, etc. - In Conclusion, with the new Strategic Path aligning on the build tool is one building block. 
2) Opinion within the team - has been discussed in several rounds, in the end majority goes towards Gradle.
3) Stakeholder Feedback - as some of our Stakeholders have to build the EDC package by their own, there was a preference towards aligning the build tool.

As you can see in the history, this decision has not been made in a rush but by thinking of all pros and cons (i.e. nr. 1 - 3).

2023-03-09 16:44 UTC, merged